name: task_id_week_04
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+2
  sqlite3: ^2.4.6
  sqllite_table_builder: ^0.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  # the material Icons class.
  uses-material-design: true
  assets:
  - assets/images/
  
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
